In [2]:
import numpy as np
import pandas as pd
import requests
from io import StringIO

In [28]:
url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv"

headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}

req = requests.get(url, headers=headers)
data = StringIO(req.text)
df = pd.read_csv(data)

In [29]:
df.sample(5)

    age  gender review education purchased
43   27    Male   Poor        PG        No
49   25  Female   Good        UG        No
48   39  Female   Good        UG       Yes
33   89  Female   Good        PG       Yes
31   22  Female   Poor    School       Yes

In [30]:
df = df.iloc[:,2:]

In [31]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [34]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
x_train

     review education
18     Good    School
28     Poor    School
16     Poor        UG
14     Poor        PG
9      Good        UG
29  Average        UG
37  Average        PG
31     Poor    School
19     Poor        PG
6      Good    School
0   Average    School
8   Average        UG
34  Average    School
49     Good        UG
41     Good        PG
22     Poor        PG
26     Poor        PG
1      Poor        UG
27     Poor        PG
44  Average        UG
23     Good    School
12     Poor    School
38     Good    School
43     Poor        PG
2      Good        PG
3      Good        PG
13  Average    School
46     Poor        PG
20  Average    School
40     Good    School
42     Good        PG
15     Poor        UG
45     Poor        PG
30  Average        UG
10     Good        UG
35     Poor    School
4   Average        UG
11     Good        UG
24  Average        PG
48     Good        UG

In [36]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [38]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [39]:
x_train = oe.transform(x_train)

In [40]:
x_train

array([[2., 0.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [2., 1.]])

In [41]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [42]:
x_train

array([[2., 0.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [2., 1.]])